java_ram: "-Xmx2g"
refadpt: phix,adapters
ktrim: r
k: 23
mink: 11
hdist: 1
qtrim: rl
trimq: 16
pigz: t
unpigz: t
overwrite: t
ordered: f
minlen: 55
klist: "21,33,55"
skip_ec: ""

# params for hmm filtering:
bits: 0
evalue: 1
cov: 0

# params for interval_finder.py
interval: 5000